name: Publish Node.js Package to Github and NPM

on:
  push:
    branches:
      - master
    paths: "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check if version changed
        id: version_changed
        run: |
          VERSION_OLD=$(git show ${{ github.event.before }}:package.json | jq -r .version)
          VERSION_NEW=$(jq -r .version package.json)
          if [ "$VERSION_OLD" != "$VERSION_NEW" ]; then
            echo "Version changed from $VERSION_OLD to $VERSION_NEW"
            echo "{changed}={true}" >> $GITHUB_OUTPUT
          else
            echo "Version did not change"
            echo "{changed}={false}" >> $GITHUB_OUTPUT
          fi
      - run: npm i
      - name: Publish to npm
        if: steps.version_changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
